//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.FusedConnection.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid Id { get; set; }
        public string Owner { get; set; }
        public string Name { get; set; }
        public string Mime { get; set; }
        public System.DateTime CreatedUtc { get; set; }
        public string Exif { get; set; }
        public string Path { get; set; }
        public Nullable<long> Size { get; set; }
    }
}
